### PR TITLE
Graphlab algorithms

### PR DESCRIPTION
**Pull request by Erackron**
Tested implementations for all Graphalytics algorithms on the GraphLab Create Platform, except for the ForestFire Model.

### CODE REVIEW

**Comment by Erackron** [comment]
It seems the tribler CI server can't run the GraphLab related tests because it doesn't have GraphLab Create installed. (Maven dependencies are unfortunately not of much use here).
How should we solve this?

**Comment by mihaic** [comment]
I will ask the administrator to install GraphLab Create. Is `pip install graphlab-create==1.3` + product key enough?

**Comment by Erackron** [comment]
Yes, it is.

**Comment by Erackron** [comment]
Will close this and reopen when GraphLab has been installed.

**Pull request closed without merging**
